todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('user/', include('users.urls')),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('adicionar/', views.adicionar, name='adicionar'),
    path('excluir/<int:id>/', views.excluir, name='excluir'),
    path('editar/<int:id>', views.editar, name='editar'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('sair/', views.sair, name='sair')
]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Lista(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    detalhes = models.TextField()
    date_modified = models.DateTimeField(auto_now=True, null=True)
    crated_at = models.DateTimeField(auto_now_add=True, null=True)
    done = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title)

users/models.py
from django.db import models

# Create your models here.

todo_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Lista
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
@login_required(login_url="/user/login/")
def home(request):
    lista = Lista.objects.all().filter(user=request.user).order_by('-id')

    busca = request.GET.get('search')

    if busca:
        lista = lista.filter(title__icontains=busca)

    paginator = Paginator(lista, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    if request.method == 'POST':
        busca = request.POST.get('search') 
        if busca:
            lista = lista.filter(title__icontains=busca)

        checks = request.POST.getlist('check')
        
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        for valor in page_obj.object_list:
            valor.done = True
            valor.save()
        
        for valor in page_obj.object_list:
            if str(valor.id) not in checks:
                valor.done = False
                valor.save()
        
        return redirect(f'/?page={page_obj.number}&search={busca}')



    return render(request, 'index.html', context={'lista': lista, 'user': request.user, 'logado': request.user.is_authenticated, "page_obj": page_obj})

def adicionar(request):
    if request.method == 'GET':
        return render(request, 'adicionar.html', context={'logado': request.user.is_authenticated})
    else:
        title = request.POST.get('title')
        description = request.POST.get('descricao')
        if not title or not description:
            return redirect('/adicionar')
        
        todo = Lista(user=request.user, title=title, detalhes=description)
        todo.save()
        return redirect('/')
    
def excluir(request, id):
    tarefa = get_object_or_404(Lista, id=id, user=request.user)
    if request.method == 'POST':
        tarefa.delete()
        return redirect('todo_app:home')
    return render(request, 'excluir.html', {'tarefa': tarefa, 'logado': request.user.is_authenticated})

def editar(request, id):
    tarefa = get_object_or_404(Lista, id=id, user=request.user)
    if request.method == "GET":
        return render(request, 'editar.html', {'tarefa': tarefa})
    if request.method == "POST":
        titulo = request.POST.get('title')
        descricao = request.POST.get('descricao')

        tarefa.title = titulo
        tarefa.detalhes = descricao
        tarefa.save()
        return redirect('/')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.messages import constants
from django.contrib import messages

def register(request):
    if request.method == 'GET':
        return render(request, 'register.html', {'logado': request.user.is_authenticated})
    
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if User.objects.filter(username=username).exists():
            messages.add_message(request, constants.ERROR, 'Esse nome de usuário já existe!')
            return redirect('/user/')
        
        if len(password) < 3:
            messages.add_message(request, constants.ERROR, 'A senha deve ter 3 ou mais dígitos!')
            return redirect('/user/')
        
        if User.objects.filter(email=email).exists():
            messages.add_message(request, constants.ERROR, 'Esse email já está em uso!')
            return redirect('/user/')

        usuario = User(first_name=name, email=email, username=username)
        usuario.set_password(password)  # Criptografar a senha
        usuario.save()
        return redirect('/user/login')

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html', context={'logado': request.user.is_authenticated})
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(request, username=username, password=password)

        if user:
            auth.login(request, user)
            return redirect('/')
        
        messages.add_message(request, constants.ERROR, 'Credenciais inválidas!')
        return redirect('/user/login')
        
def sair(request):
    auth.logout(request)
    return redirect('/user/login')

todo_app/templates/adicionar.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
   <link rel="stylesheet" href="{% static "todo/adicionar.css" %}"> 
{% endblock css %}

{% block content %}
    <div class="principal">
        <div class="barra">
            <div class="cabecalho">
                <h2>Crie uma tarefa: </h2>
                <a href="{% url "todo_app:home" %}"><b><p id="voltar">x</p></b></a>
            </div>
            
            <div class="lista">
                
                <div class="todo">
                    <div class="tarefa">
                        
                        
                        <form action="{% url "todo_app:adicionar" %}" method='POST'>
                        <h3 class="description">Título:</h3>
                        {% csrf_token %}
                        <input type="text" name="title" class="barra-pesquisa" placeholder="Digite o Titulo da sua tarefa...">
                        <h3 id="descricao" class="description">Descrição:</h3>
                        <textarea name="descricao" placeholder="faça uma descrição legal e bem explicativa :)" class="barra-pesquisa caixa-maior"></textarea>
                    </div>
                        <div class="checkbox-div">
                            <input type="submit" class="botao" value="Criar">
                            </form>
                        </div>
                    </div> 
                </div>
            </div>
        </div>    
    </div>
{% endblock content %}

todo_app/templates/editar.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
   <link rel="stylesheet" href="{% static "todo/adicionar.css" %}"> 
{% endblock css %}

{% block content %}
    <div class="principal">
        <div class="barra">
            <div class="cabecalho">
                <h2>Edite a tarefa:</h2>
                <a href="{% url "todo_app:home" %}"><b><p id="voltar">x</p></b></a>
            </div>
            
            <div class="lista">
                
                <div class="todo">
                    <div class="tarefa">
                        
                        
                        <form action="{% url "todo_app:editar" tarefa.id %}" method='POST' id="pesquisa-form">
                        <h3 class="description">Título:</h3>
                        {% csrf_token %}
                        <input type="text" name="title" class="barra-pesquisa" value="{{tarefa.title}}">
                        <h3 id="descricao" class="description">Descrição:</h3>
                        <textarea name="descricao" class="barra-pesquisa caixa-maior">{{tarefa.detalhes}}</textarea>
                    </div>
                        <div class="checkbox-div">
                            <input type="submit" class="botao" value="Editar">
                            </form>
                        </div>
                    </div> 
                </div>
            </div>
        </div>    
    </div>
{% endblock content %}

todo_app/templates/excluir.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
   <link rel="stylesheet" href="{% static "todo/excluir.css" %}"> 
{% endblock css %}


{% block content %}
    <div class="principal">
        <div class="barra">
            <a href="{% url "todo_app:home" %}"><b><p id="voltar">x</p></b></a>
            <div class="lista">
                <h2>Deseja excluir esta tarefa?</h2>
                <div class="todo">
                    <div class="tarefa">
                        
                        <b><h1 class="texts" id="titulo2">{{tarefa.title}}</h1></b>
                        <b><h3 class="texts">{{tarefa.detalhes}}</h3></b>
                        
                    </div>
                        
                    </div> 
                    <div class="checkbox-div">
                        <form method="POST" action="{% url 'todo_app:excluir' tarefa.id %}">
                            {% csrf_token %}
                            <input type="submit" value="Sim" class="botao">
                        </form>
                        <a href="{% url "todo_app:home" %}"><input type="submit" value="Não" class="botao"></a>
                    </div>
                </div>
                
            </div>
        </div>    
    </div>
{% endblock content %}

todo_app/templates/index.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
   <link rel="stylesheet" href="{% static "todo/todo.css" %}"> 
{% endblock css %}

{% block content %}
    <div class="principal">
        <div class="barra">
            <h1 class="titulo">To-Do do {{user.first_name}}</h1>
            <div class="pesquisa-superior">
                <div class="pesquisa">
                    <div class="form">
                        <form action="" method="GET">
                            <input type="search" placeholder="Buscar tarefa" name='search' class="barra-pesquisa" value="{{ request.GET.search }}">
                            <input type="submit" value="Buscar" class="botao">
                        </form>
                    </div>
                    <a href="{% url "todo_app:adicionar" %}"><button class="botao adicionar">Adicionar</button></a>
                </div>
            </div>
            <div class="lista">
                <form action="{% url "todo_app:home" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="search" value="{{ request.GET.search }}">
                    {% if page_obj %}
                        {% for tarefa in page_obj %}
                            <div class="todo">
                                <div class="tarefa">
                                    <h1 class='nome-tarefa'> {{tarefa.title}} </h1>
                                    <p id="descricao">{{tarefa.detalhes}}</p>
                                </div>
                                <div class="checkbox-div">
                                    <input type="checkbox" value="{{ tarefa.id }}" name="check" id="feito" {% if tarefa.done %}checked{% endif %}>
                                </div>
                            </div>
                            <div class="tarefa data" {% if tarefa.done %} id='green' {% else %} id='orange' {% endif %}>
                                <p>tarefa criada em: <b>{{ tarefa.crated_at }}</b></p>
                                <div id="alteracoes">
                                    <a href="{% url 'todo_app:editar' tarefa.id %}" value={{ tarefa.id }}"><p>editar</p></a>
                                    <a href="{% url 'todo_app:excluir' tarefa.id %}" value={{ tarefa.id }}"><p>excluir</p></a>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="tarefa-vazia">
                            <h1> Lista vazia </h1>
                            <p id="descricao">Use o botão "Adicionar" para adicionar elementos na lista</p>
                        </div>
                    {% endif %}
                    <div>
                        <input type="submit" class="botao adicionar atualizar" value="Atualizar" name="atualizar" id="botao1">
                        <div class="pagination-input">
                            <div class="pagination">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1&search={{ request.GET.search }}">&laquo; primeira</a>
                                        <a href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}">anterior</a>
                                    {% endif %}

                                    <span class="current">
                                        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                                    </span>

                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}">próxima</a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}">última &raquo;</a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/login.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "user/login.css" %}">
{% endblock css %}

{% block content %}
    <div class="container-log">
        <div class="form-container">
            <h1>LOGIN</h1>
            {% if messages %}
                <br>
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
            <form action="{% url "users:login" %}" method="post">
                {% csrf_token %}
                <input type="text" placeholder="username..." class="input-box" name="username" required>
                <br>
                <br>
                <input type="password" placeholder="password..." class="input-box" name="password" required>
                <br>
                <br>
                <input type="submit" class="button-submit" value="Login">
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/register.html
{% extends "base/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "user/register.css" %}">
{% endblock css %}

{% block content %}
    <div class="container-log">
        <div class="form-container">
            <h1>REGISTRO</h1>
            {% if messages %}
                <br>
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
            <form action="{% url "users:register" %}" method="post">
                {% csrf_token %}
                <input type="text" placeholder="your name..." class="input-box" name="name" required>
                <br>
                <br>
                <input type="email" placeholder="email..." class="input-box" name="email" required>
                <br>
                <br>
                <input type="text" placeholder="username..." class="input-box" name="username" required>
                <br>
                <br>
                <input type="password" placeholder="password..." class="input-box" name="password" required>
                <br>
                <br>
                <input type="submit" class="button-submit" value="register" required>
            </form>
        </div>
    </div>
{% endblock content %}